name: CMake Build

on:
  push:
    branches: [ master ]

jobs:
  build-mingw32:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64-i686 g++-mingw-w64-i686 ninja-build

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: |
        cd build
        cmake .. -G "Ninja" \
          -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc \
          -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++ \
          -DCMAKE_MAKE_PROGRAM=ninja \
          -DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE \
          -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++ -lstdc++ -lgcc_s"
        ninja

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mingw32-build
        path: build/

  build-mingw64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 ninja-build

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: |
        cd build
        cmake .. -G "Ninja" \
          -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
          -DCMAKE_MAKE_PROGRAM=ninja \
          -DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE \
          -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++ -lstdc++ -lgcc_s"
        ninja

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mingw64-build
        path: build/

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y cmake build-essential

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: |
        cd build
        cmake ..
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: build/
    
  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MSBuild (MSVC)
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17.0'          # Visual Studio 2022

      - name: Configure CMake
        run: |
          cmake -S . -B build `
                -G "Visual Studio 17 2022" `
                -A x64 `
                -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-msvc-build
          path: build/
